import type { Metadata } from "next";
import Image from "next/image";
import { Poppins } from "next/font/google";
import "./globals.css";

const popins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${popins.variable}`}>
        <header style={{textAlign: "center"}}>
            <Image
                src="/logo.svg"
                alt="flying plane"
                width={150}
                height={150}
            />

            <h2>Search flights</h2>
        </header>
        {children}
      </body>
    </html>
  );
}
